# Generated by Django 4.0.2 on 2022-05-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReseñas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='reseña',
            field=models.TextField(max_length=240),
        ),
    ]
