# Generated by Django 4.0.2 on 2022-05-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReseñas', '0002_alter_pelicula_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='autor',
            field=models.CharField(default='', max_length=40),
        ),
    ]
